title: "Stress Burner"
description: "Reduce stress, prevent burnout, and reclaim joy with easy, elegant self-care."
author: "Unyong Kim"
email: "unyong@stressburner.me"
url: "https://www.stressburner.me" # custom domain
baseurl: "" # root of domain
logo: "/assets/images/stress-burner-logo.svg"

twitter:
  username: stressburner
  card: summary_large_image

defaults:
  - scope:
      path: ""
    values:
      image: "/assets/images/stress-burner-book.jpg"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Navigation
nav:
  - title: Home
    url: /
  - title: Course
    url: /course/
  - title: Book
    url: /book/
  - title: Client Comments
    url: /testimonials/
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# External links
purchase_url: https://stressburner.systeme.io/126ed7cc
student_portal_url: https://stressburner.systeme.io/school/course/stressburnerblueprint/
purchase_coaching_url: https://stressburner.systeme.io/126ed7cc
purchase_modules_url: https://stressburner.systeme.io/126ed7cc-f8323b20
